### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by skanwal** [manabuishii/vim-cwl#3]
Hi,

I am trying to setup vim support for cwl. I have followed the `Manual Installation` as mentioned on the main page but could not see any changes in the vim cwl syntax.

Is there anything I am missing? 
Thanks.

**Comment by manabuishii** [comment]
@skanwal Which version of vim do you use ?

**Comment by skanwal** [comment]
The version is:
`VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 21 2016 17:10:41)`

**Comment by manabuishii** [comment]
@skanwal Thanks for reporting !!
I can reproduce same problem.
The reason why we can not get CWL syntax highlight is directory structure problem.
And I create solution.

My vim version is

```
version 8.0.1401
```

I think you already do the README instalation process.
That process create usual file.
Firsty remove these files.

```
rm ~/.vim/syntax
rm ~/.vim/ftdetect
mkdir -p ~/.vim/ftplugin
```

After that create directory and copy the files to directories.

```
mkdir -p ~/.vim/syntax
mkdir -p ~/.vim/ftdetect
mkdir -p ~/.vim/ftplugin
git clone https://github.com/manabuishii/vim-cwl /tmp/vim-cwl
cp /tmp/vim-cwl/syntax/cwl.vim ~/.vim/syntax
cp /tmp/vim-cwl/ftdetect/cwl.vim ~/.vim/ftdetect
cp /tmp/vim-cwl/ftplugin/cwl.vim ~/.vim/ftplugin
```

**Comment by skanwal** [comment]
Yay! That worked. Thanks!

**Comment by manabuishii** [comment]
@skanwal Thanks !!
